version: '3.7'

services:
  db: 
    restart: always
    image: postgres
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'

  backend:
    container_name: backend
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/usr/src/backend/
    ports:
      - '8000:8000'
    env_file: 
      - ./backend/.env
    depends_on:
      - db 
    links:
      - db:db