version: '3.7'

services:
  db: 
    restart: always
    image: postgres
    container_name: db
    env_file:
      - ./backend/.env
    networks: 
      - backend-net

  backend:
    container_name: backend
    build: ./backend
    command: ./setup.sh
    env_file: 
      - ./backend/.env
    depends_on:
      - db 
    networks: 
      - backend-net

  frontend: 
    container_name: frontend 
    build: ./frontend
    ports: 
      - 3000:3000
  
  nginx:
    container_name: secure_nginx
    build: ./nginx
    ports: 
      - 80:80
    networks: 
      - backend-net
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - db 
      - backend

networks: 
  backend-net: {}
