version: '3.7'

services:
  db: 
    restart: always
    image: postgres
    container_name: db
    env_file:
      - ./backend/.env
    networks: 
      - backend-net

  backend:
    container_name: backend
    build: ./backend
    command: python3 manage.py runserver
    volumes: 
      - ./backend:/usr/src/backend/
    env_file: 
      - ./backend/.env
    depends_on:
      - db 
    links:
      - db:db
    networks: 
      - frontend-net
      - backend-net

  frontend: 
    container_name: frontend 
    build: ./frontend
    volumes: 
      - ./frontend:/usr/src/app/
    ports: 
      - '3000:3000'
    depends_on:
      - backend
    networks: 
      - frontend-net

networks: 
  frontend-net: {}
  backend-net: {}
