version: '2'

services:
  db: 
    image: postgres
    container_name: db
    # volumes: 
    #   - ./db/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    # ports: 
    #   - '5432:5432'

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes: 
      - ./backend:/code
    ports:
      - '8000:8000'
    depends_on:
      - db 

# volumes:
#   postgres_data: