# Generated by Django 3.1.2 on 2020-11-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
