# Generated by Django 3.1.2 on 2020-11-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_parent',
            new_name='post_id',
        ),
    ]
