# Generated by Django 3.1.2 on 2020-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
