# Generated by Django 3.1.2 on 2020-11-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_backend', '0002_auto_20201115_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post_parent',
        ),
    ]
